//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaamShaam.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public System.DateTime DateTime { get; set; }
        public string WithId { get; set; }
        public string CreatedBy { get; set; }
        public bool IsAttended { get; set; }
    
        public virtual AspNetUser CreatedByUser { get; set; }
        public virtual AspNetUser WithUser { get; set; }
    }
}
