//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaamShaam.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHistory
    {
        public long Id { get; set; }
        public long JobId { get; set; }
        public string ContractorId { get; set; }
        public System.DateTime JobStartDate { get; set; }
        public System.DateTime JobEndDate { get; set; }
        public string Feedback { get; set; }
        public int JobStatus { get; set; }
        public string PurposalText { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
    }
}
