//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaamShaam.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public long Id { get; set; }
        public double Rating { get; set; }
        public string Comments { get; set; }
        public string RatedTo { get; set; }
        public string RatedBy { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsApproved { get; set; }
        public long JobId { get; set; }
        public System.DateTime EditedAt { get; set; }
    
        public virtual AspNetUser RatedByUser { get; set; }
        public virtual AspNetUser RatedToUser { get; set; }
    }
}
